//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 3/26/2010 8:25:18 PM
namespace CATALYST.Bootstrap
{
    
    /// <summary>
    /// There are no comments for Model1Container in the schema.
    /// </summary>
    public partial class Model1Container : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : 
                base("name=Model1Container", "Model1Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : 
                base(connectionString, "Model1Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Model1Container")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for TestEntityDoNotAlterSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TestEntityDoNotAlter> TestEntityDoNotAlterSet
        {
            get
            {
                if ((this._TestEntityDoNotAlterSet == null))
                {
                    this._TestEntityDoNotAlterSet = base.CreateQuery<TestEntityDoNotAlter>("[TestEntityDoNotAlterSet]");
                }
                return this._TestEntityDoNotAlterSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TestEntityDoNotAlter> _TestEntityDoNotAlterSet;
        /// <summary>
        /// There are no comments for Entity2Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Entity2> Entity2Set
        {
            get
            {
                if ((this._Entity2Set == null))
                {
                    this._Entity2Set = base.CreateQuery<Entity2>("[Entity2Set]");
                }
                return this._Entity2Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Entity2> _Entity2Set;
        /// <summary>
        /// There are no comments for Entity3Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Entity3> Entity3Set
        {
            get
            {
                if ((this._Entity3Set == null))
                {
                    this._Entity3Set = base.CreateQuery<Entity3>("[Entity3Set]");
                }
                return this._Entity3Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Entity3> _Entity3Set;
        /// <summary>
        /// There are no comments for TestEntityDoNotAlterSet in the schema.
        /// </summary>
        public void AddToTestEntityDoNotAlterSet(TestEntityDoNotAlter testEntityDoNotAlter)
        {
            base.AddObject("TestEntityDoNotAlterSet", testEntityDoNotAlter);
        }
        /// <summary>
        /// There are no comments for Entity2Set in the schema.
        /// </summary>
        public void AddToEntity2Set(Entity2 entity2)
        {
            base.AddObject("Entity2Set", entity2);
        }
        /// <summary>
        /// There are no comments for Entity3Set in the schema.
        /// </summary>
        public void AddToEntity3Set(Entity3 entity3)
        {
            base.AddObject("Entity3Set", entity3);
        }
    }
    /// <summary>
    /// There are no comments for Model1.TestEntityDoNotAlter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Key
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model1", Name="TestEntityDoNotAlter")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TestEntityDoNotAlter : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TestEntityDoNotAlter object.
        /// </summary>
        /// <param name="key">Initial value of Key.</param>
        public static TestEntityDoNotAlter CreateTestEntityDoNotAlter(int key)
        {
            TestEntityDoNotAlter testEntityDoNotAlter = new TestEntityDoNotAlter();
            testEntityDoNotAlter.Key = key;
            return testEntityDoNotAlter;
        }
        /// <summary>
        /// There are no comments for Property Key in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this._Key;
            }
            set
            {
                this.OnKeyChanging(value);
                this.ReportPropertyChanging("Key");
                this._Key = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Key");
                this.OnKeyChanged();
            }
        }
        private int _Key;
        partial void OnKeyChanging(int value);
        partial void OnKeyChanged();
        /// <summary>
        /// There are no comments for Property IsEnable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsEnable
        {
            get
            {
                return this._IsEnable;
            }
            set
            {
                this.OnIsEnableChanging(value);
                this.ReportPropertyChanging("IsEnable");
                this._IsEnable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsEnable");
                this.OnIsEnableChanged();
            }
        }
        private global::System.Nullable<bool> _IsEnable;
        partial void OnIsEnableChanging(global::System.Nullable<bool> value);
        partial void OnIsEnableChanged();
        /// <summary>
        /// There are no comments for Property ReferenceId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId
        {
            get
            {
                return this._ReferenceId;
            }
            set
            {
                this.OnReferenceIdChanging(value);
                this.ReportPropertyChanging("ReferenceId");
                this._ReferenceId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ReferenceId");
                this.OnReferenceIdChanged();
            }
        }
        private string _ReferenceId;
        partial void OnReferenceIdChanging(string value);
        partial void OnReferenceIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PublishOnDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> PublishOnDate
        {
            get
            {
                return this._PublishOnDate;
            }
            set
            {
                this.OnPublishOnDateChanging(value);
                this.ReportPropertyChanging("PublishOnDate");
                this._PublishOnDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PublishOnDate");
                this.OnPublishOnDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _PublishOnDate;
        partial void OnPublishOnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPublishOnDateChanged();
        /// <summary>
        /// There are no comments for Property ExpireAfterDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ExpireAfterDate
        {
            get
            {
                return this._ExpireAfterDate;
            }
            set
            {
                this.OnExpireAfterDateChanging(value);
                this.ReportPropertyChanging("ExpireAfterDate");
                this._ExpireAfterDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ExpireAfterDate");
                this.OnExpireAfterDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ExpireAfterDate;
        partial void OnExpireAfterDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExpireAfterDateChanged();
        /// <summary>
        /// There are no comments for Property FullsizeImage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FullsizeImage
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._FullsizeImage);
            }
            set
            {
                this.OnFullsizeImageChanging(value);
                this.ReportPropertyChanging("FullsizeImage");
                this._FullsizeImage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FullsizeImage");
                this.OnFullsizeImageChanged();
            }
        }
        private byte[] _FullsizeImage;
        partial void OnFullsizeImageChanging(byte[] value);
        partial void OnFullsizeImageChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailImage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ThumbnailImage
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._ThumbnailImage);
            }
            set
            {
                this.OnThumbnailImageChanging(value);
                this.ReportPropertyChanging("ThumbnailImage");
                this._ThumbnailImage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ThumbnailImage");
                this.OnThumbnailImageChanged();
            }
        }
        private byte[] _ThumbnailImage;
        partial void OnThumbnailImageChanging(byte[] value);
        partial void OnThumbnailImageChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
    /// <summary>
    /// There are no comments for Model1.Entity2 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model1", Name="Entity2")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Entity2 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Entity2 object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Entity2 CreateEntity2(int id)
        {
            Entity2 entity2 = new Entity2();
            entity2.Id = id;
            return entity2;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
    }
    /// <summary>
    /// There are no comments for Model1.Entity3 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model1", Name="Entity3")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Entity3 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Entity3 object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Entity3 CreateEntity3(int id)
        {
            Entity3 entity3 = new Entity3();
            entity3.Id = id;
            return entity3;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
    }
}
